pipeline {
    agent any

    // env {
    //     def myString = "This is example string!"
    // }

    stages {
        stage('CleanUp') {
            steps {
                deleteDir()
                exampleFunction("This is example string! from ckeanUp stage.")
            }
        }

        stage('Build') {
            steps {
                echo "Faza Build"
            }
        }

        stage('Deploy') {
            steps {
                echo "Faza Deploy"
            }
        }

        stage('Test') {
            steps {
                echo "Faza Test"
            }
        }

        stage('Release') {
            steps {
                echo "Faza Release"
            }
        }
    }
}

def exampleFunction(String exampleText) {
    echo "exampleText jest wyswietlany jako: ${exampleText}"
}
