pipeline {
    agent any

    env {
        def number = 121
    }

    stages {
        stage('CleanUp') {
            steps {
                deleteDir()
                exampleFunction("This is example string! from ckeanUp stage.")
            }
        }

        stage('Build') {
            steps {
                script {
                    if (params.number == 121) {
                        currentBuild.result = "SUCCESS!!!"
                        return
                    }
                    else {
                        echo "number is not equal 121, so Build is faild"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Faza Deploy"
            }
        }

        stage('Test') {
            steps {
                echo "Faza Test"
            }
        }

        stage('Release') {
            steps {
                echo "Faza Release"
            }
        }
    }
}

def exampleFunction(String exampleText) {
    echo "exampleText jest wyswietlany jako: ${exampleText}"
}
